// permissions.ts
export const PERMISSIONS = {
  super_admin: {
    menus: [
      "main",
      "manuals",
      "role",
      "management",
      "finances",
      "default",
      "analitika",
      "user_balance",
      "deposit",
      "orders",
      "clients",
      "drivers",
      "merchants",
      "user_reviews",
      "regions",
      "districts",
      "machines",
      "specifications",
      "pricing",
      "params_filter",
      "moderators",
    ],
    actions: {
      pricing: ["create", "edit", "delete", "status"],
      tax_amount: ["button", "create", "edit", "delete"],
      clients: ["view", "edit", "delete", "status"],
      districts: ["view", "edit", "delete", "create", "status"],
      drivers: ["create", "view", "edit", "delete", "status"],
      machines: ["create", "view", "edit", "delete", "status"],
      orders: ["view", "cancel"],
      user_balance: ["edit"],
      deposit: ["view"],
      regions: ["view", "edit", "delete", "create", "status", "search"],
      specifications: ["view", "edit", "delete", "create", "status"],
      params_filter: ["create", "edit", "delete", "status"],
      moderators: ["create", "edit", "delete", "status"],
    },
  },
  admin: {
    menus: [
      "main",
      "manuals",
      "role",
      "management",
      "finances",
      "default",
      "analitika",
      "user_balance",
      "deposit",
      "orders",
      "clients",
      "drivers",
      "merchants",
      "user_reviews",
      "regions",
      "districts",
      "machines",
      "specifications",
      "pricing",
      "params_filter",
      "moderators",
    ],
    actions: {
      pricing: ["create", "edit", "delete", "status"],
      tax_amount: ["button", "create", "edit", "delete"],
      clients: ["view", "edit", "delete", "status"],
      districts: ["view", "edit", "delete", "create", "status"],
      drivers: ["create", "view", "edit", "delete", "status"],
      machines: ["create", "view", "edit", "delete", "status"],
      orders: ["view", "cancel"],
      user_balance: ["edit"],
      deposit: ["view"],
      regions: ["view", "edit", "delete", "create", "status", "search"],
      specifications: ["view", "edit", "delete", "create", "status"],
      params_filter: ["create", "edit", "delete", "status"],
      moderators: ["create", "edit", "delete", "status"],
    },
  },
  operator: {
    menus: [
      "main",
      "manuals",
      // "role",
      // "management",
      // "finances",
      "default",
      // "analitika",
      // "user_balance",
      // "deposit",
      "orders",
      // "clients",
      // "drivers",
      // "merchants",
      // "user_reviews",
      // "regions",
      // "districts",
      // "machines",
      "specifications",
      // "pricing",
      // "params_filter",
      // "moderators",
    ],
    actions: {
      orders: ["view", "cancel"],
    },
  },
  finance: {
    menus: [
      "main",
      "manuals",
      "management",
      "finances",
      "default",
      "analitika",
      "user_balance",
      "deposit",
      "orders",
      "clients",
      "drivers",
      "merchants",
      "user_reviews",
      "regions",
      "districts",
      "machines",
      "specifications",
      "pricing",
      "params_filter",
    ],
    actions: {},
  },
  accauntant: {
    menus: [
      "main",
      "manuals",
      "management",
      "finances",
      "default",
      "analitika",
      "user_balance",
      "deposit",
      "orders",
      "clients",
      "drivers",
      "merchants",
      "user_reviews",
      "pricing",
    ],
    actions: {
      // pricing: ["create", "edit", "delete", "status"],
      // tax_amount: ["button", "create", "edit", "delete"],
      // clients: ["view", "edit", "delete"],
      // districts: ["view", "edit", "delete", "create", "status"],
      // drivers: ["create", "view", "edit", "delete", "status"],
      // machines: ["create", "view", "edit", "delete", "status"],
      // orders: ["view", "cancel"],
      // user_balance: ["edit"],
      // deposit: ["view"],
      // regions: ["view", "edit", "delete", "create", "status", "search"],
      // specifications: ["view", "edit", "delete", "create", "status"],
      // params_filter: ["create", "edit", "delete", "status"],
      // moderators: ["create", "edit", "delete", "status"],
    },
  },
  moderator: {
    menus: [
      "main",
      "manuals",
      "role",
      "management",
      "clients",
      "drivers",
      "user_reviews",
      // "finances",
      // "default",
      // "analitika",
      // "user_balance",
      // "deposit",
      // "orders",
      // "merchants",
      // "pricing",
    ],
    actions: {
      // pricing: ["create", "edit", "delete", "status"],
      // tax_amount: ["button", "create", "edit", "delete"],
      // clients: ["view", "edit", "delete"],
      // districts: ["view", "edit", "delete", "create", "status"],
      // drivers: ["create", "view", "edit", "delete", "status"],
      // machines: ["create", "view", "edit", "delete", "status"],
      // orders: ["view", "cancel"],
      // user_balance: ["edit"],
      // deposit: ["view"],
      // regions: ["view", "edit", "delete", "create", "status", "search"],
      // specifications: ["view", "edit", "delete", "create", "status"],
      // params_filter: ["create", "edit", "delete", "status"],
      // moderators: ["create", "edit", "delete", "status"],
    },
  },
};
